version: 2
jobs:
  build:
    working_directory: ~/circleci-pylint_md
    docker:
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo pip install pylint
      - run: "python ~/circleci-pylint_md/pylint_md.py -l ~/circleci-pylint_md -o ~/circleci-pylint_md/test-results/results.md"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
